import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, "../../..");
const CORE_TEST_DIR = path.resolve(__dirname, "..");

// Chrome profiles (userDataDir) write hundreds of small files per second
// (LevelDB, SQLite, cache). When the repo lives in a cloud-synced folder
// (Dropbox, etc.), that write volume gets intercepted for sync on every
// write and Chrome effectively hangs. Ephemeral run state lives outside the
// repo entirely; only static, low-churn things (the patched extension
// build, fixtures) stay under the repo.
// Per-run so two concurrent runs (two terminals, or a local run alongside a
// CI one) can't delete each other's test-build mid-flight. The runner loads
// this config first, so it seeds the id; global-setup, the workers and the
// fixture server are all child processes that inherit it through the
// environment, which keeps them agreed on one directory without IPC.
const RUN_ID = process.env.MEETREMOTE_TEST_RUN_ID ?? String(process.pid);
process.env.MEETREMOTE_TEST_RUN_ID = RUN_ID;

const RUNTIME_DIR = path.join(os.tmpdir(), `meetremote-test-core-${RUN_ID}`);

// The already-built extension. This harness never edits it — it only reads
// it to produce a patched copy (see TEST_BUILD_DIR) for content-script
// injection into local fixtures.
export const BUILD_DIR = path.resolve(ROOT_DIR, "build");

// Copy of BUILD_DIR with the content_scripts match pattern widened to
// include FIXTURE_ORIGIN, so content.js/elements.js run against our local
// fixtures instead of requiring a real meet.google.com tab. The original
// manifest.json and ./build are never modified. Regenerated by
// global-setup.js on every run, so it lives outside the repo too.
export const TEST_BUILD_DIR = path.join(RUNTIME_DIR, "test-build");

export const FIXTURES_DIR = path.resolve(CORE_TEST_DIR, "fixtures");

// The one fixture global-setup.js keeps out of the content-script injection,
// so tests can exercise what the popup does when a matching tab has no
// content script listening. See global-setup.js and send-failure.spec.js.
export const UNINJECTED_FIXTURE = "no-content-script.html";

// Fixed (not ephemeral) so global-setup.js and playwright.config.js's
// webServer can agree on it without cross-process IPC.
export const FIXTURE_PORT = 34567;
export const FIXTURE_ORIGIN = `http://127.0.0.1:${FIXTURE_PORT}`;

export const OUTPUT_DIR = path.join(RUNTIME_DIR, "test-results");
